### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by dudusakharovich** [grafana-wizzy/wizzy#132]
Where do I need to install the Wizzy module ? On a server with Grafana installed on it ? Or on a separate server ?

**Comment by foxylion** [comment]
Wizzy is a command line tool, you must only install it locally.
Afterwards it uses the Grafana API to backup/restore your dashboards/...

**Comment by dudusakharovich** [comment]
@foxylion - Does it support the new Grafana version & dashboards ?

**Comment by foxylion** [comment]
Yes, but folders are not yet supported.

**Comment by Sytten** [comment]
Closing this has been answered
