### ISSUE TITLE
Export is broken for datasources if the name contains blabla.something

### ISSUE THREAD

**Issue by aned** [grafana-wizzy/wizzy#133]
wizzy export datasources
✘ Datasource file datasources/somedashboard02.json does not exist.

cd datasources/
ls | grep somedashboard02
somedashboard02.corp.json

I had to remove .corp from every json name file than export worked.

**Comment by Sytten** [comment]
Fixed by 71ffd58ed923067daf2d45b601967489ec34dd5c
