### ISSUE TITLE
Error extracting row in v0.6.0

### ISSUE THREAD

**Issue by argentito** [grafana-wizzy/wizzy#137]
$ wizzy extract row 4 

/usr/local/lib/node_modules/wizzy/src/local/dashboards.js:133
		var srcRow = srcRows[srcRowNumber-1];
		                    ^
TypeError: Cannot read property '3' of undefined

srcDashboard.rows does not exist

**Comment by Sytten** [comment]
Duplicate of https://github.com/grafana-wizzy/wizzy/issues/129
