### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by Sytten** [grafana-wizzy/wizzy#147]
It would be nice to have some insight from the creator (@utkarshcmu). If you need a maintainer, the community needs to know...

**Comment by Sytten** [comment]
I sent an email to @utkarshcmu to see if we can have an active maintainer. Otherwise a fork will be necessary.

**Comment by tinder-ubhatnagar** [comment]
I would love to add someone maintainers to the project as I am short on time these days, any volunteers?

**Comment by Sytten** [comment]
I have time for that, I think @johnsudaar also has time. The best would be create a public organization and transfer the project to it.
We would also need to setup NPM so we can do releases. 
references:
https://docs.npmjs.com/creating-an-org
https://help.github.com/en/articles/creating-a-new-organization-from-scratch

**Comment by johnsudaar** [comment]
I've a bit of time left. So if i can help it would be my pleasure.

**Comment by Sytten** [comment]
@tinder-ubhatnagar let me know when you create the organizations so we can setup CI and publish a new version of wizzy.

**Comment by Sytten** [comment]
So we have an org now (https://github.com/grafana-wizzy), waiting for @utkarshcmu to move the repo there. We still miss an npm org so we can setup CI.

**Comment by utkarshcmu** [comment]
Moved to https://github.com/grafana-wizzy/wizzy

**Comment by Sytten** [comment]
We have the npm org too! Now the only remaining thing is move the npm project and setup CI. I signed up for the github actions, but I am still unsure if we will be able to use it for a while. In the meantime we can setup travis or circle.

**Comment by Sytten** [comment]
We also need to move the website repo to grafana-wizzy so we can update the documentation @utkarshcmu

**Comment by Sytten** [comment]
Ok so what is still missing:
- Package moved to the grafana-wizzy org on npm
- Documentation website moved to the grafana-wizzy org on github
- Application for github actions on the grafana-wizzy org (optional, we can use circleci for now)

**Comment by Sytten** [comment]
We have a new domain: grafana-wizzy.com
The only missing part is the npm package then I can close the issue

**Comment by HackToHell** [comment]
Dockerhub also needs to be updated, the current one is broker.

**Comment by Sytten** [comment]
Agreed, I will create it when I have release rights. Still waiting for that.

**Comment by tinder-ubhatnagar** [comment]
Hi guys, I am not a PRO at NPM orgs and packages, I have given maintainer permissions to the NPM org https://www.npmjs.com/settings/grafana-wizzy/packages to @Sytten . I think now next steps will be to modify package.json in this repo and then try npm publish.

**Comment by Sytten** [comment]
Thanks!!! We can work with that :)
