### ISSUE TITLE
Org Descriptors

### ISSUE THREAD

**Issue by aayush-ag21** [grafana-wizzy/wizzy#158]
Could we add a feature of adding more descriptors to organizations and datasources like who the admin users are.

**Comment by Sytten** [comment]
We are limited by the API of grafana, can you check what is possible and come up with a more detailed proposal?

**Comment by Sytten** [comment]
We are limited by the API of grafana, can you check what is possible and come up with a more detailed proposal?

**Comment by aayush-ag21** [comment]
Sure, some of the other APIs that can be added are:
GET /api/org/users
PATCH /api/org/users/:userId
GET /api/org/users/lookup
and lots of others on https://grafana.com/docs/http_api/org/
