### ISSUE TITLE
Bump the version and include new features in the release from current master

### ISSUE THREAD

**Issue by PeterSzegedi** [grafana-wizzy/wizzy#167]
Hi all,

First of all, thanks for the great library, it makes managing our config as code much easier.
It seems to me that the 0.6.0 version is behind the master.
The feature of folder management have been merged in https://github.com/grafana-wizzy/wizzy/pull/125 to master, but it is not in the npm repo yet. This is causing a bit of headache because npm install will not pull the latest changes and we are really into folders. 

Btw, I have tested https://github.com/grafana-wizzy/wizzy/pull/125 locally and it seems OK to me. 

Could you consider bumping the release from master?

Thanks,
Peter

**Comment by Sytten** [comment]
Hi! Yes I have to do that, but working like crazy right now. Sunday is my deadline, I will automate the process.

**Comment by PeterSzegedi** [comment]
Awesome, thanks for the update @Sytten! :)

**Comment by Sytten** [comment]
I am very sorry for the slow responsiveness, I am working on the release right now. Expect it in the next few hours.

**Comment by Sytten** [comment]
Its done, now all new release will be automatically published!

**Comment by PeterSzegedi** [comment]
Thanks @Sytten
